# Generated by Django 3.2.4 on 2021-07-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETE', '0004_rename_image_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='JAGUARETE.Product'),
        ),
    ]
