# Generated by Django 3.2.4 on 2021-07-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETE', '0005_alter_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
